### ISSUE TITLE
import earthpy.spatial raising NotImplementedError

### ISSUE THREAD

**Issue by joemcglinchy** [earthlab/earthpy#169]
Hi, has anyone seen this?? running jupyter notebook from the earthpy parent directory:

```
!ls earthpy/

returns:
CONTRIBUTING.rst
CONTRIBUTORS.rst
dev-requirements.txt
docs
earthpy
environment.yml
LICENSE
pyproject.toml
README.md
setup.py
```

just showing that to give an idea of my file structure. This first import statement raises a NotImplementedError (the second one, imports fine after trying it *twice*, the first try to import it throws the same error):

```
from earthpy.earthpy import spatial as es
from earthpy.earthpy.spatial import stack
```

throws:

```
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-1-96e8a3644ff9> in <module>()
----> 1 from earthpy.earthpy.spatial import stack
      2 import os, sys
      3 import glob

C:\Projects\earth_py_support\joe_fork_github\earthpy\earthpy\__init__.py in <module>()
     13 
     14 from pkg_resources import resource_string
---> 15 epsg = json.loads(resource_string("earthpy", "example-data/epsg.json").decode("utf-8"))

C:\software\Anaconda3\envs\eapy_gbdx\lib\site-packages\pkg_resources\__init__.py in resource_string(self, package_or_requirement, resource_name)
   1236         """Return specified resource as a string"""
   1237         return get_provider(package_or_requirement).get_resource_string(
-> 1238             self, resource_name
   1239         )
   1240 

C:\software\Anaconda3\envs\eapy_gbdx\lib\site-packages\pkg_resources\__init__.py in get_resource_string(self, manager, resource_name)
   1480 
   1481     def get_resource_string(self, manager, resource_name):
-> 1482         return self._get(self._fn(self.module_path, resource_name))
   1483 
   1484     def has_resource(self, resource_name):

C:\software\Anaconda3\envs\eapy_gbdx\lib\site-packages\pkg_resources\__init__.py in _get(self, path)
   1558             return self.loader.get_data(path)
   1559         raise NotImplementedError(
-> 1560             "Can't perform this operation for loaders without 'get_data()'"
   1561         )
   1562 

NotImplementedError: Can't perform this operation for loaders without 'get_data()'
```

This is specific to jupyter notebook. If I am in a command line python interpreter and try to import the spatial modules I get:

```
>>> from earthpy.earthpy import spatial as es
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Projects\earth_py_support\joe_fork_github\earthpy\earthpy\__init__.py", line 3, in <module>
    from .io import EarthlabData  # , list_files
  File "C:\Projects\earth_py_support\joe_fork_github\earthpy\earthpy\io.py", line 10, in <module>
    from download import download
ModuleNotFoundError: No module named 'download'
```

Have there been a bunch of changes since this morning where I should update my master branch and make a new feature branch with the stack functionality?

**Comment by lwasser** [comment]
@joemcglinchy did you sort this out?
`import earthpy.spatial as es` should work.
