### ISSUE TITLE
pip installation problem. TypeError: 'encoding' is an invalid keyword argument for this function

### ISSUE THREAD

**Issue by bibinwil** [earthlab/earthpy#232]
Hi, I'm using 
Ubuntu 16.04.5 LTS 64-bit
python 2.7.12

I tried installing earthpy using
`pip install --upgrade git+https://github.com/earthlab/earthpy.git`

And I get the following error
gpu@gpu-Z270X-Ultra-Gaming:~/PycharmProjects/Bathy$ pip2.7 install --upgrade git+https://github.com/earthlab/earthpy.git
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting git+https://github.com/earthlab/earthpy.git
  Cloning https://github.com/earthlab/earthpy.git to /tmp/pip-req-build-Ud2syr
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  Complete output from command /usr/bin/python /usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpqE8GPG:
  Traceback (most recent call last):
    File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py", line 207, in <module>
      main()
    File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py", line 197, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py", line 54, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-aDejb1/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 130, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/tmp/pip-build-env-aDejb1/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 112, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-aDejb1/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 126, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 29, in <module>
      with open(path.join(this_directory, "README.md"), encoding="utf-8") as f:
  TypeError: 'encoding' is an invalid keyword argument for this function
  
  ----------------------------------------
Command "/usr/bin/python /usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpqE8GPG" failed with error code 1 in /tmp/pip-req-build-Ud2syr
You are using pip version 19.0.1, however version 19.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

I tried in python 3.5, 3.7 and even in anaconda. Nothing working. 

even tried by using PyCharm to different environments, no hope. Please help

**Comment by lwasser** [comment]
hey @bibinwil  just a note that we don't support python v 2.7 . Can you provide the output that you get when installing using python 3.6 or higher?

**Comment by bibinwil** [comment]
Hi, I got installed in python 3.5 and 3.7. But when I tried to import it, it's showing the following error

import earthpy
Traceback (most recent call last):
  File "/usr/lib/python3.5/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "/snap/pycharm-professional/112/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/earthpy/__init__.py", line 7, in <module>
    from . import utils, spatial
  File "/snap/pycharm-professional/112/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/snap/pycharm-professional/112/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/earthpy/utils.py", line 2, in <module>
    import numpy as np
  File "/snap/pycharm-professional/112/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/home/gpu/.local/lib/python3.5/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/snap/pycharm-professional/112/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/snap/pycharm-professional/112/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/home/gpu/.local/lib/python3.5/site-packages/numpy/core/__init__.py", line 57, in <module>
    from . import numerictypes as nt
  File "/snap/pycharm-professional/112/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/snap/pycharm-professional/112/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/home/gpu/.local/lib/python3.5/site-packages/numpy/core/numerictypes.py", line 111, in <module>
    from ._type_aliases import (
  File "/snap/pycharm-professional/112/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/home/gpu/.local/lib/python3.5/site-packages/numpy/core/_type_aliases.py", line 63, in <module>
    _concrete_types = {v.type for k, v in _concrete_typeinfo.items()}
  File "/home/gpu/.local/lib/python3.5/site-packages/numpy/core/_type_aliases.py", line 63, in <setcomp>
    _concrete_types = {v.type for k, v in _concrete_typeinfo.items()}
AttributeError: 'tuple' object has no attribute 'type'

**Comment by mbjoseph** [comment]
Hi @bibinwil - thanks for opening this issue! I have not been able to replicate this locally, but the easiest way to install EarthPy is by installing its dependencies via [conda](https://conda.io/en/latest/miniconda.html) first, then installing the package. 

Have you tried using a conda environment with earthpy? e.g., 

1. Install the `earthpy-dev` conda environment, activate it, and install EarthPy:

```bash
conda env create -f environment.yml
conda activate earthpy-dev
pip install --upgrade git+https://github.com/earthlab/earthpy.git
```

2. Then in PyCharm, choose the `earthpy-dev` conda environment for your project: https://www.jetbrains.com/help/pycharm/conda-support-creating-conda-virtual-environment.html

**Comment by lwasser** [comment]
I am going to close this issue as it's not been active for over a month! @bibinwil please re-open it if you have tried the above suggestions and it's still not working for you!
`pip install earthpy` should also work at this point!
