### ISSUE TITLE
Docs build error -- clip vignette

### ISSUE THREAD

**Issue by lwasser** [earthlab/earthpy#413]
when trying to build the docs, i run itno an issue:

```
Warning, treated as error:
/Users/leahwasser/github/0-python/earthpy/examples/plot_clip.py failed to execute correctly: Traceback (most recent call last):
  File "/Users/leahwasser/miniconda3/envs/earthpy-dev/lib/python3.6/site-packages/sphinx_gallery/gen_rst.py", line 480, in _memory_usage
    out = func()
  File "/Users/leahwasser/miniconda3/envs/earthpy-dev/lib/python3.6/site-packages/sphinx_gallery/gen_rst.py", line 465, in __call__
    exec(self.code, self.globals)
  File "/Users/leahwasser/github/0-python/earthpy/examples/plot_clip.py", line 79, in <module>
    roads = gpd.read_file(road_path)
  File "/Users/leahwasser/miniconda3/envs/earthpy-dev/lib/python3.6/site-packages/geopandas/io/file.py", line 77, in read_file
    with reader(path_or_bytes, **kwargs) as features:
  File "/Users/leahwasser/miniconda3/envs/earthpy-dev/lib/python3.6/site-packages/fiona/env.py", line 397, in wrapper
    return f(*args, **kwargs)
  File "/Users/leahwasser/miniconda3/envs/earthpy-dev/lib/python3.6/site-packages/fiona/__init__.py", line 253, in open
    layer=layer, enabled_drivers=enabled_drivers, **kwargs)
  File "/Users/leahwasser/miniconda3/envs/earthpy-dev/lib/python3.6/site-packages/fiona/collection.py", line 159, in __init__
    self.session.start(self, **kwargs)
  File "fiona/ogrext.pyx", line 484, in fiona.ogrext.Session.start
  File "fiona/_shim.pyx", line 80, in fiona._shim.gdal_open_vector
fiona.errors.DriverError: data/spatial-vector-lidar/global/ne_10m_roads/ne_10m_n_america_roads.shp: No such file or directory

```

the example vignette tries to import a data file that doesn't seem to exist in the build. Please have a look at that vignette and let me know @nkorinek if the data exist in the earthpy download!

**Comment by lwasser** [comment]
this issue is no longer relevant given we have redone the clip vignette and given it to geopandas as a part of #429 closing now.
